# fly.toml app configuration file generated for tve-registration on 2025-06-09T16:18:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tve-registration'
primary_region = 'fra'

[build]

[[mounts]]
  source = 'tmp'
  destination = '/tmp'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "20s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/actuator/health"

[[vm]]
  memory = '1g'
  cpu_kind = 'shared'
  cpus = 1
